FROM node:16-alpine3.11

# Set the timezone in docker
RUN apk --no-cache add tzdata && \
        cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
        echo "Asia/Seoul" > /etc/timezone

WORKDIR /app

# COPY package*.json ./
COPY . .

RUN npm install --force
# RUN npm i -g @quasar/cli

CMD [ "npm", "run", "dev"]
EXPOSE 9000
