insert into dotori.book (book_id, author, book_img, role_cnt, title, summary)
values  (1, '저자 미상', 'https://dotori.online/images/books/rabbit-and-turtle.png', 3, '토끼와 거북이', '''토끼와 거북이''는 꾸준함과 인내의 중요성을 가르쳐주는 유명한 동화입니다. 토끼는 자신의 빠른 속도를 자랑하며 거북이를 무시했습니다. 그래서 거북이는 토끼에게 경주를 제안합니다. 토끼는 자신의 승리를 너무 확신하여 중간에 쉬었고, 그 사이에 거북이는 천천히 그러나 꾸준히 앞으로 나아갔습니다. 토끼가 깨어났을 때, 거북이는 이미 결승선을 통과했습니다. 이 동화는 ''빠르게 달리는 것이 항상 승리를 의미하지 않으며, 꾸준히 노력하는 것이 결국에는 성공으로 이어진다''는 교훈을 전해줍니다.'),
        (2, '이솝', 'https://dotori.online/images/books/lion-and-rat.png', 3, '사자와 생쥐', '''사자와 생쥐''는 이솝우화에서 가장 유명한 이야기 중 하나입니다. 한 번, 사자가 생쥐를 잡아먹으려 했지만, 생쥐는 자신이 나중에 사자를 도울 수 있을 것을 약속하며 목숨을 구걸했습니다. 사자는 웃으며 생쥐를 놓아주었습니다. 시간이 흘러 사자가 사냥꾼의 그물에 걸려 위험에 처했을 때, 생쥐가 나타나 그물을 갉아먹어 사자를 구해주었습니다. 이 이야기는 ''''아무리 작고 약해 보이는 존재라도 그 가치를 무시해서는 안 된다''''는 교훈을 주며, 서로에게 도움을 줄 수 있는 관계의 중요성을 강조합니다.'),
        (4, '이솝', 'https://dotori.online/images/books/flog-and-cow.jpg', 3, '황소와 개구리', '준비 중입니다.'),
        (5, '이솝', 'https://dotori.online/images/books/sly-fox.jpg', 2, '꾀 많은 여우', '준비 중입니다.'),
        (6, '이솝', 'https://dotori.online/images/books/fox-and-grape.jpg', 3, '여우와 신 포도', '준비 중입니다.'),
        (7, '이솝', 'https://dotori.online/images/books/shepherd-boy.jpg', 3, '양치기 소년', '준비 중입니다.'),
        (8, '이솝', 'https://dotori.online/images/books/wind-and-sun.jpg', 3, '북풍과 태양', '준비 중입니다.'),
        (9, '이솝', 'https://dotori.online/images/books/the-ant-and-the-grasshopper.jpg', 3, '개미와 베짱이', '준비 중입니다.'),
        (10, '이솝', 'https://dotori.online/images/books/belling-the-cat.jpg', 4, '고양이 목에 방울달기', '준비 중입니다.'),
        (11, '이솝', 'https://dotori.online/images/books/foolish-donkey.jpg', 3, '어리석은 당나귀', '준비 중입니다.'),
        (12, '이솝', 'https://dotori.online/images/books/wolf-and-young-sheep.jpg', 3, '늑대와 어린양', '준비 중입니다.'),
        (13, '이솝', 'https://dotori.online/images/books/flying-turtle.jpg', 2, '하늘을 날고 싶은 거북이', '준비 중입니다.'),
        (14, '테스트', 'https://dotori.online/images/books/test.png', 1, '테스트책', '테스트'),
        (15, '저자 미상', 'https://dotori.online/images/books/brother-sister-sun-and-moon.png', 3, '해와 달이 된 오누이', '준비 중입니다.'),
        (16, '안데르센', 'https://dotori.online/images/books/naked-king.png', 4, '벌거벗은 임금님', '준비 중입니다.'),
        (17, '저자 미상', 'https://dotori.online/images/books/jack-and-bean-tree.png', 3, '잭과 콩나무', '준비 중입니다.'),
        (18, '안데르센', 'https://dotori.online/images/books/ugly-duckling.png', 4, '미운 오리새끼', '준비 중입니다.'),
        (19, '조지프 제이콥스', 'https://dotori.online/images/books/three-litte-pigs.png', 4, '아기돼지 삼형제', '준비 중입니다.'),
        (20, '저자 미상', 'https://dotori.online/images/books/hansel-and-gretel.png', 4, '헨젤과 그레텔', '준비 중입니다.'),
        (21, '안데르센', 'https://dotori.online/images/books/match-girl.png', 3, '성냥팔이 소녀', '준비 중입니다.'),
        (22, '위다', 'https://dotori.online/images/books/dog-of-flanders.png', 4, '플랜더스의 개', '준비 중입니다.'),
        (23, '저자 미상', 'https://dotori.online/images/books/kongji-and-padji.png', 4, '콩쥐 팥쥐', '준비 중입니다.'),
        (24, '저자 미상', 'https://dotori.online/images/books/gold-ax-and-silver-ax.png', 3, '금도끼 은도끼', '준비 중입니다.');