spring:
  config:
    import:
      - application-db.yml
      - application-security.yml
      - application-video.yml
      - application-openvidu.yml

management:
  endpoints:
    base-path: /api/actuator
    web:
      exposure:
        include: health
        exclude: '*'

---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: green
server:
  port: 8082
