spring:
  config:
    import:
      - application-db.yml
      - application-security.yml
      - application-video.yml
      - application-openvidu.yml

management:
  endpoints:
    base-path: /api
    web:
      exposure:
        include: health
        exclude: '*'