spring:
  profiles:
    active: blue
  config:
    import:
      - application-db.yml
      - application-security.yml
      - application-video.yml
      - application-openvidu.yml

management:
  endpoints:
    base-path: /api
    web:
      exposure:
        include: health
        exclude: '*'

---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: ${GREEN_SERVER_PORT}

---
spring:
  config:
    activate:
      on-profile: green
server:
  port: ${BLUE_SERVER_PORT}